//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAnimal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int Id { get; set; }
        public string AnimalName { get; set; }
        public int ColorId { get; set; }
        public int SpeciesId { get; set; }
        public int ProvinceId { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Province Province { get; set; }
        public virtual Species Species { get; set; }
    }
}
